import AssistantQA from "../models/assistantModel.js";
import OpenAI from "openai";

// Ask AI (Database-based with OpenRouter fallback)
export const askAI = async (req, res) => {
  try {
    const { question } = req.body;
    if (!question)
      return res.status(400).json({ message: "Question is required" });

    console.log("📝 Question received:", question);

    // ✅ Step 1: Search in database first
    const result = await AssistantQA.find(
      { $text: { $search: question } },
      { score: { $meta: "textScore" } }
    )
      .sort({ score: { $meta: "textScore" } })
      .limit(1);

    // ✅ If found in database, return it
    if (result.length > 0) {
      console.log("✅ Answer found in database");
      return res.status(200).json({ 
        answer: result[0].answer,
        source: "database"
      });
    }

    console.log("⚠️ No answer in database, using OpenRouter AI...");

    // ✅ Step 2: If not found, use OpenRouter API
    if (!process.env.OPENROUTER_API_KEY) {
      return res.status(200).json({
        answer: "Sorry, I couldn't find an answer for that. Please contact support.",
        source: "none"
      });
    }

    // Initialize OpenRouter client here (after dotenv is loaded)
    const client = new OpenAI({
      apiKey: process.env.OPENROUTER_API_KEY,
      baseURL: 'https://openrouter.ai/api/v1'
    });

    const completion = await client.chat.completions.create({
      model: 'meta-llama/llama-3.2-3b-instruct:free',
      messages: [
        {
          role: 'system',
          content: 'You are a helpful university academic assistant. Answer questions concisely and accurately. If the question is not related to academics or university matters, politely redirect to appropriate channels.'
        },
        {
          role: 'user',
          content: question
        }
      ]
    });

    const aiAnswer = completion.choices[0].message.content;

    console.log("✅ Answer generated by OpenRouter AI");

    return res.status(200).json({
      answer: aiAnswer,
      source: "openrouter"
    });

  } catch (error) {
    console.error("❌ Assistant Controller Error:", error);
    
    // Handle specific API errors
    if (error.message?.includes("API key") || error.message?.includes("credentials")) {
      return res.status(500).json({ 
        message: "AI service configuration error. Please contact support.",
        error: "API key issue" 
      });
    }

    res.status(500).json({ 
      message: "Sorry, I encountered an error processing your question.",
      error: error.message 
    });
  }
};

// Add new Q&A (Admin only)
export const addQA = async (req, res) => {
  try {
    const { question, answer, tags } = req.body;
    if (!question || !answer)
      return res.status(400).json({ message: "Both fields are required" });

    const newQA = new AssistantQA({ question, answer, tags });
    await newQA.save();

    res.status(201).json({ message: "FAQ added successfully", newQA });
  } catch (error) {
    console.error("Assistant Controller Error:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};
